import type { Metadata } from "next";
import { Bagel_Fat_One, Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/src/shared/Layout";
import { getFigmaStyles } from "@/utils/queries/getFigmaStyles";
import { convertColorPalette } from "@/utils/services/convertColorPalette";
import { getFigmaComponents } from "@/utils/queries/getFigmaComponents";
import { convertComponentToIconURL } from "@/utils/services/convertComponentToIconURL";
import useColorStore from "@/utils/stores/useColorPaletteStore";
import useIconURLStore from "@/utils/stores/useIconURLStore";

const inter = Bagel_Fat_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function useFigmaColors() {
  const styles = await getFigmaStyles();
  const colorPalette = convertColorPalette(styles);
  return { colorPalette };
}

async function useFigmaIcons() {
  const iconComponents = await getFigmaComponents();
  const iconURLs = await convertComponentToIconURL(iconComponents);
  return { iconURLs };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { colorPalette } = await useFigmaColors();
  const { iconURLs } = await useFigmaIcons();

  useColorStore.setState({ colorPalette });
  useIconURLStore.setState({ iconURLs });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
