import type {Metadata} from 'next';
// eslint-disable-next-line camelcase
import {Bagel_Fat_One} from 'next/font/google';
import './globals.css';
import {ReactNode} from 'react';
import {useColors, useIcons} from '@/shared/api';
import {useColorPaletteStore, useIconStore} from '@/shared/stores';
import {BottomNavigator} from '@/widgets';

const inter = Bagel_Fat_One({weight: '400', subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function MobileContainer({children}: {children: ReactNode}) {
  return (
    <div
      style={{
        maxWidth: 390,
        marginLeft: 'auto',
        marginRight: 'auto',
        backgroundColor: '#FF4911',
        position: 'relative',
        height: '100%',
      }}
    >
      {children}
      <BottomNavigator />
    </div>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const {colorPalette} = await useColors();
  const {icons} = await useIcons();

  useColorPaletteStore.setState({colorPalette});
  useIconStore.setState({icons});

  return (
    <html lang="en">
      <body className={inter.className}>
        <MobileContainer>{children}</MobileContainer>
      </body>
    </html>
  );
}
