import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {ReactNode} from 'react';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function MobileContainer({children}: {children: ReactNode}) {
  return (
    <div
      style={{
        maxWidth: 390,
        margin: '0 auto',
        backgroundColor: '#FF4911',
        position: 'relative',
      }}
    >
      {children}
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MobileContainer>{children}</MobileContainer>
      </body>
    </html>
  );
}
